SELECT AIN.ANIMAL_ID
     , AIN.ANIMAL_TYPE
     , AIN.NAME
  FROM ANIMAL_INS AS AIN
  LEFT JOIN ANIMAL_OUTS AS AOUT
    ON AIN.ANIMAL_ID = AOUT.ANIMAL_ID
 WHERE AIN.SEX_UPON_INTAKE != AOUT.SEX_UPON_OUTCOME
 ORDER BY AIN.ANIMAL_ID ASC;
