SELECT AIN.ANIMAL_TYPE
     , CASE AIN.NAME IS NULL
       WHEN TRUE
       THEN 'No name'
       ELSE AIN.NAME
        END AS 'NAME'
     , AIN.SEX_UPON_INTAKE
  FROM ANIMAL_INS AS AIN
 ORDER BY AIN.ANIMAL_ID ASC;
